language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: ''
# command to run tests, e.g. python setup.py test

script:
   -     cd src
   -     rm -rf local_backup/Wed_Oct_30_2013_GMT___Full   Dropbox/backups*/Wed_Oct_30_2013_GMT___Full
   -     python ./unit_test.py  -r backup_report.py
   -     cd ..
